Refactor for Asynchronous control flow
The motivation for this commit is when
Rollbar registered the following error:
```
java.lang.NullPointerException: Attempt to invoke virtual method
'void com.google.android.gms.maps.GoogleMap.moveCamera(
    com.google.android.gms.maps.CameraUpdate)'
on a null object reference

at org.azavea.otm.ui.MainMapFragment.lambda$null$3
    (MainMapFragment.java:488)
```

It's undoubtedly a race condition, one of several.
Tame the asynchronous control flow to eliminate race conditions.

AFAIK, this fixes all race conditions except open question #1 below.
Unknown how many rollbar errors it will eliminate, but should
eliminate the original npe.

Refer to
* [MapView](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView)
* [GoogleMap](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap)
* [MapsInitializer](https://developers.google.com/android/reference/com/google/android/gms/maps/MapsInitializer)
* [GoogleApiAvailability](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability)
* [Fragment Life Cycle](https://developer.android.com/guide/components/fragments.html)

Changes:

- Follow instructions on the Android Fragment life cycle
- Follow instructions on the Google API state machine
- Consolidate most initialization in `onActivityCreated`
  from `onCreateView` and `onResume`
- Use jDeferred to synchronize between asynchronous flows
- Eliminate mMap member variable in favor of the deferred.
- Thanks to all of the above, eliminate checks for whether
  the map, the instance, and the location have been initialized
- Replace `clearTileCache`, which no longer worked (#291),
  with `reloadTiles`
- Eliminate `MainMapFragment.onHiddenChanged`
- Fix pre-existing bug on Back Stack pop out of step 3 of add tree
- Move some string literals used in toasts into `strings.xml`
- Remove unnecessary `public` declarations
- Better `Logger` messages
- Use `lambda`s more extensively
- Fix pre-existing bug in `TreeEditDisplay` to update the rev
  on the correct plot variable
- Update `MapHelper` to use current google availability api

--

Connects to #294